server:
  port: ${PORT:7501}

spring:
  datasource:
    url: jdbc:postgresql://localhost:10001/emss
    username: msg_user
    password: msg_user
  flyway:
    url: jdbc:postgresql://localhost:10001/emss
    user: msg_user
    password: msg_user
    schemas: messaging
    baseline-on-migrate: true

springdoc:
  swagger-ui:
    path: /swagger.html